# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20151108_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content_de',
            field=models.TextField(null=True, verbose_name='Inhalt'),
        ),
        migrations.AddField(
            model_name='entry',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Inhalt'),
        ),
        migrations.AddField(
            model_name='entry',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Inhalt'),
        ),
        migrations.AddField(
            model_name='entry',
            name='title_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='entry',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='entry',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Titel'),
        ),
    ]
