# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:27
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='website',
            field=models.URLField(blank=True, verbose_name='Veranstaltungswebsite'),
        ),
        migrations.AlterField(
            model_name='fair',
            name='end',
            field=models.DateTimeField(verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='fair',
            name='hall',
            field=models.CharField(blank=True, max_length=255, verbose_name='Halle'),
        ),
        migrations.AlterField(
            model_name='fair',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name der Messe'),
        ),
        migrations.AlterField(
            model_name='fair',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='fair',
            name='stand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stand'),
        ),
        migrations.AlterField(
            model_name='fair',
            name='start',
            field=models.DateTimeField(verbose_name='Beginn'),
        ),
    ]
