# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0002_auto_20160131_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fair',
            name='end',
            field=models.DateField(verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='fair',
            name='start',
            field=models.DateField(verbose_name='Beginn'),
        ),
    ]
