# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairs', '0003_auto_20160131_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='fair',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='fair',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='fair',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name der Messe'),
        ),
        migrations.AddField(
            model_name='fair',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name der Messe'),
        ),
        migrations.AddField(
            model_name='fair',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name der Messe'),
        ),
    ]
