# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SawBlade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('quality', models.CharField(max_length=255, verbose_name='Qualität')),
                ('ind_2301_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_2302_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_2352_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_2402_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_3302_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_3352_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_3402_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_3354_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_3404_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_3454_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4354_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4404_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4454_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4356_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4406_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4456_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4476_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4409_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4459_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4509_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4559_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4451_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4501_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_4551_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5501_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5551_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5571_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5504_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5554_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5574_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5604_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5654_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5704_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5707_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_5628_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_6658_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_6708_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_6758_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_6801_hss', models.BooleanField(verbose_name='HSS?')),
                ('ind_6954_hss', models.BooleanField(verbose_name='HSS?')),
            ],
            options={
                'verbose_name': 'Sägeblatt',
                'verbose_name_plural': 'Sägeblätter',
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Buchstabe')),
                ('value', models.CharField(max_length=255, verbose_name='Zahl')),
            ],
            options={
                'verbose_name': 'Zahn',
                'verbose_name_plural': 'Zähne',
            },
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_2301',
            field=models.ManyToManyField(blank=True, related_name='ind_2301', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_2302',
            field=models.ManyToManyField(blank=True, related_name='ind_2302', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_2352',
            field=models.ManyToManyField(blank=True, related_name='ind_2352', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_2402',
            field=models.ManyToManyField(blank=True, related_name='ind_2402', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_3302',
            field=models.ManyToManyField(blank=True, related_name='ind_3302', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_3352',
            field=models.ManyToManyField(blank=True, related_name='ind_3352', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_3354',
            field=models.ManyToManyField(blank=True, related_name='ind_3354', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_3402',
            field=models.ManyToManyField(blank=True, related_name='ind_3402', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_3404',
            field=models.ManyToManyField(blank=True, related_name='ind_3404', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_3454',
            field=models.ManyToManyField(blank=True, related_name='ind_3454', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4354',
            field=models.ManyToManyField(blank=True, related_name='ind_4354', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4356',
            field=models.ManyToManyField(blank=True, related_name='ind_4356', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4404',
            field=models.ManyToManyField(blank=True, related_name='ind_4404', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4406',
            field=models.ManyToManyField(blank=True, related_name='ind_4406', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4409',
            field=models.ManyToManyField(blank=True, related_name='ind_4409', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4451',
            field=models.ManyToManyField(blank=True, related_name='ind_4451', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4454',
            field=models.ManyToManyField(blank=True, related_name='ind_4454', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4456',
            field=models.ManyToManyField(blank=True, related_name='ind_4456', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4459',
            field=models.ManyToManyField(blank=True, related_name='ind_4459', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4476',
            field=models.ManyToManyField(blank=True, related_name='ind_4476', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4501',
            field=models.ManyToManyField(blank=True, related_name='ind_4501', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4509',
            field=models.ManyToManyField(blank=True, related_name='ind_4509', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4551',
            field=models.ManyToManyField(blank=True, related_name='ind_4551', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_4559',
            field=models.ManyToManyField(blank=True, related_name='ind_4559', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5501',
            field=models.ManyToManyField(blank=True, related_name='ind_5501', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5504',
            field=models.ManyToManyField(blank=True, related_name='ind_5504', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5551',
            field=models.ManyToManyField(blank=True, related_name='ind_5551', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5554',
            field=models.ManyToManyField(blank=True, related_name='ind_5554', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5571',
            field=models.ManyToManyField(blank=True, related_name='ind_5571', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5574',
            field=models.ManyToManyField(blank=True, related_name='ind_5574', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5604',
            field=models.ManyToManyField(blank=True, related_name='ind_5604', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5628',
            field=models.ManyToManyField(blank=True, related_name='ind_5628', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5654',
            field=models.ManyToManyField(blank=True, related_name='ind_5654', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5704',
            field=models.ManyToManyField(blank=True, related_name='ind_5704', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_5707',
            field=models.ManyToManyField(blank=True, related_name='ind_5707', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_6658',
            field=models.ManyToManyField(blank=True, related_name='ind_6658', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_6708',
            field=models.ManyToManyField(blank=True, related_name='ind_6708', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_6758',
            field=models.ManyToManyField(blank=True, related_name='ind_6758', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_6801',
            field=models.ManyToManyField(blank=True, related_name='ind_6801', to='products.Tooth'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='ind_6954',
            field=models.ManyToManyField(blank=True, related_name='ind_6954', to='products.Tooth'),
        ),
    ]
