# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20151124_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('number',), 'verbose_name': 'Kennziffer', 'verbose_name_plural': 'Kennziffer'},
        ),
        migrations.AlterModelOptions(
            name='tooth',
            options={'ordering': ('name',), 'verbose_name': 'Zahn', 'verbose_name_plural': 'Zähne'},
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='teeth',
        ),
        migrations.AddField(
            model_name='indicator',
            name='teeth',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Zähne'),
        ),
    ]
