# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20151124_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='diameter',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Durchmesser'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='value',
            field=models.CharField(max_length=1024, verbose_name='Kennziffer'),
        ),
    ]
