# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20151124_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='C',
            field=models.BooleanField(default=False, verbose_name='C'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='E',
            field=models.BooleanField(default=False, verbose_name='E'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='G',
            field=models.BooleanField(default=False, verbose_name='G'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='H',
            field=models.BooleanField(default=False, verbose_name='H'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='I',
            field=models.BooleanField(default=False, verbose_name='I'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='J',
            field=models.BooleanField(default=False, verbose_name='J'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='L',
            field=models.BooleanField(default=False, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='N',
            field=models.BooleanField(default=False, verbose_name='N'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='O',
            field=models.BooleanField(default=False, verbose_name='O'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='T',
            field=models.BooleanField(default=False, verbose_name='T'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='U',
            field=models.BooleanField(default=False, verbose_name='U'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='UE',
            field=models.BooleanField(default=False, verbose_name='Ü'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='V',
            field=models.BooleanField(default=False, verbose_name='V'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='W',
            field=models.BooleanField(default=False, verbose_name='W'),
        ),
    ]
