# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-26 16:59
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20151126_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawblade',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
    ]
