# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sawblade_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='length',
            field=models.IntegerField(blank=True, default=0, verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='width',
            field=models.IntegerField(blank=True, default=0, verbose_name='Breite'),
        ),
    ]
