# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20151126_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='hss',
        ),
        migrations.AddField(
            model_name='sawblade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Abbildung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aufnahme'),
        ),
    ]
