# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0002_auto_20150606_2003'),
        ('products', '0011_auto_20151126_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawblade',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Abbildung', to='filer.Image'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aufnahme'),
        ),
    ]
