# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20151204_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawblade',
            name='clamping',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Aufnahme'),
        ),
        migrations.AlterField(
            model_name='sawblade',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Produktabbildung'),
        ),
    ]
