# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20151204_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sawblade',
            old_name='clamping',
            new_name='clamping_img',
        ),
    ]
