# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:43
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20151204_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawblade',
            name='clamping',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='type'),
        ),
    ]
