# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20151204_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clamping',
            options={'verbose_name': 'Aufnahme', 'verbose_name_plural': 'Aufnahmen'},
        ),
        migrations.AlterField(
            model_name='sawblade',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='sawblade',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Clamping', verbose_name='Aufnahme'),
        ),
    ]
