# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20151204_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sawblade',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='products.Indicator', verbose_name='Kennziffern'),
        ),
    ]
