# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20151204_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='diameter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Durchmesser'),
        ),
    ]
