# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20151227_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sawblade',
            old_name='type',
            new_name='clamping',
        ),
    ]
