# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:08
from __future__ import unicode_literals

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20151227_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='Beschreibung')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Produktabbildung')),
            ],
            options={
                'verbose_name': 'Produktgruppe',
                'verbose_name_plural': 'Produktgruppen',
            },
        ),
        migrations.AlterField(
            model_name='sawblade',
            name='type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductGroup', verbose_name='Produktgruppe'),
        ),
    ]
