# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20151227_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich?'),
        ),
    ]
