# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productgroup_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='M',
            field=models.BooleanField(default=False, verbose_name='M'),
        ),
    ]
