# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_indicator_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sawblade',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
    ]
