# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_sablesawblade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sablesawblade',
            name='toothing',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verzahnung'),
        ),
    ]
