# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_sablesawblade_cutting_minerals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sablesawblade',
            name='cutting_metal',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Schnittbereich Metall'),
        ),
        migrations.AlterField(
            model_name='sablesawblade',
            name='cutting_wood',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Schnittbereich Holz'),
        ),
    ]
