# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20160102_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sawblade',
            name='description',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Beschreibung'),
        ),
    ]
