# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 16:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20160102_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackSawBlade',
            fields=[
                ('sablesawblade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.SableSawBlade')),
            ],
            options={
                'verbose_name_plural': 'Metallhandsägeblätter',
                'verbose_name': 'Metallhandsägeblatt',
            },
            bases=('products.sablesawblade',),
        ),
    ]
