# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20160112_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sawblade',
            name='quality',
            field=models.CharField(max_length=255, verbose_name='Stahlsorte'),
        ),
    ]
