# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_hacksawblade_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sawblade',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bezeichnung'),
        ),
    ]
