# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_sawblade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleSaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernr', models.CharField(max_length=1024, verbose_name='Bestellnr.')),
                ('description', models.TextField(blank=True, max_length=1024, verbose_name='Beschreibung')),
                ('category', models.CharField(blank=True, max_length=1024, verbose_name='Kategorie')),
                ('mounting', models.CharField(blank=True, max_length=1024, verbose_name='Aufnahmeschaft')),
                ('saw_length', models.CharField(blank=True, max_length=1024, verbose_name='Lochsägenlänge')),
                ('pilot_drill_length', models.CharField(blank=True, max_length=1024, verbose_name='Zentrierbohrerlänge')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Abbildung')),
            ],
            options={
                'verbose_name': 'Lochsäge',
                'verbose_name_plural': 'Lochsägen',
            },
        ),
    ]
