# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20160115_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holesaw',
            name='diameter',
            field=models.ManyToManyField(blank=True, to='products.HoleSawDiameter', verbose_name='Durchmesser in mm'),
        ),
    ]
