# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20160115_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holesaw',
            name='diameter',
        ),
    ]
