# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_remove_holesaw_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='holesawdiameter',
            name='blades',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.HoleSaw'),
        ),
    ]
