# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_holesawdiameter_blades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holesawdiameter',
            name='blades',
        ),
        migrations.AddField(
            model_name='holesaw',
            name='diameter',
            field=models.ManyToManyField(blank=True, to='products.HoleSawDiameter', verbose_name='Durchmesser in mm'),
        ),
    ]
