# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20160115_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holesawdiameter',
            options={'verbose_name': 'Lochsägen-Durchmesser', 'verbose_name_plural': 'Lochsägen-Durchmesser'},
        ),
        migrations.RemoveField(
            model_name='holesaw',
            name='diameter',
        ),
        migrations.AddField(
            model_name='holesawdiameter',
            name='blades',
            field=models.ManyToManyField(blank=True, to='products.HoleSaw', verbose_name='Lochsäge'),
        ),
    ]
