# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20160115_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='holesawdiameter',
            name='alu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alu'),
        ),
        migrations.AddField(
            model_name='holesawdiameter',
            name='iron',
            field=models.IntegerField(blank=True, null=True, verbose_name='Guss'),
        ),
        migrations.AddField(
            model_name='holesawdiameter',
            name='niro',
            field=models.IntegerField(blank=True, null=True, verbose_name='NIRO'),
        ),
        migrations.AddField(
            model_name='holesawdiameter',
            name='non_ferrous_metals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buntmetalle'),
        ),
        migrations.AddField(
            model_name='holesawdiameter',
            name='steel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stahl'),
        ),
    ]
