# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20160117_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holesawdiameter',
            name='advice',
            field=models.BooleanField(default=True, verbose_name='Aus Empfehlungstabelle?'),
        ),
    ]
