# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20160117_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandSawBlade',
            fields=[
                ('sawblade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.SawBlade')),
                ('type_description', models.CharField(blank=True, max_length=255, verbose_name='Typ Beschreibung')),
                ('type2', models.CharField(blank=True, max_length=255, verbose_name='2. Typ')),
                ('type2_description', models.CharField(blank=True, max_length=255, verbose_name='2. Typ Beschreibung')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='2. Produktabbildung')),
            ],
            options={
                'verbose_name_plural': 'Sägebänder',
                'verbose_name': 'Sägeband',
            },
            bases=('products.sawblade',),
        ),
        migrations.CreateModel(
            name='BandSawBladeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Kennziffer')),
                ('width', models.IntegerField(blank=True, default=0, verbose_name='Breite')),
                ('strength', models.FloatField(blank=True, default=0, verbose_name='Stärke')),
                ('E', models.CharField(blank=True, max_length=255, verbose_name='E')),
                ('G', models.CharField(blank=True, max_length=255, verbose_name='G')),
                ('H', models.CharField(blank=True, max_length=255, verbose_name='H')),
                ('I', models.CharField(blank=True, max_length=255, verbose_name='I')),
                ('J', models.CharField(blank=True, max_length=255, verbose_name='J')),
                ('L', models.CharField(blank=True, max_length=255, verbose_name='L')),
                ('N', models.CharField(blank=True, max_length=255, verbose_name='N')),
                ('O', models.CharField(blank=True, max_length=255, verbose_name='O')),
                ('T', models.CharField(blank=True, max_length=255, verbose_name='T')),
                ('U', models.CharField(blank=True, max_length=255, verbose_name='U')),
                ('V', models.CharField(blank=True, max_length=255, verbose_name='V')),
                ('W', models.CharField(blank=True, max_length=255, verbose_name='W')),
            ],
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='bandsaw_indicators',
            field=models.ManyToManyField(blank=True, to='products.BandSawBladeIndicator', verbose_name='Kenziffern'),
        ),
    ]
