# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_auto_20160118_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandsawbladeindicator',
            options={'verbose_name': 'Sägeband-Kennziffer', 'verbose_name_plural': 'Sägeband-Kennziffer'},
        ),
        migrations.AddField(
            model_name='bandsawbladeindicator',
            name='A',
            field=models.CharField(blank=True, max_length=255, verbose_name='A'),
        ),
        migrations.AddField(
            model_name='bandsawbladeindicator',
            name='C',
            field=models.CharField(blank=True, max_length=255, verbose_name='C'),
        ),
        migrations.AddField(
            model_name='bandsawbladeindicator',
            name='X',
            field=models.CharField(blank=True, max_length=255, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='bandsawbladeindicator',
            name='Y',
            field=models.CharField(blank=True, max_length=255, verbose_name='Y'),
        ),
        migrations.AddField(
            model_name='bandsawbladeindicator',
            name='Z',
            field=models.CharField(blank=True, max_length=255, verbose_name='Z'),
        ),
        migrations.AlterField(
            model_name='bandsawbladeindicator',
            name='strength',
            field=models.FloatField(blank=True, default=0, verbose_name='Stärke (in mm)'),
        ),
        migrations.AlterField(
            model_name='bandsawbladeindicator',
            name='width',
            field=models.IntegerField(blank=True, default=0, verbose_name='Breite (in mm)'),
        ),
        migrations.AlterField(
            model_name='holesawdiameter',
            name='diameter',
            field=models.IntegerField(verbose_name='Durchmesser (in mm)'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='diameter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Durchmesser (in mm)'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='length',
            field=models.IntegerField(blank=True, default=0, verbose_name='Länge (in mm)'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='strength',
            field=models.FloatField(blank=True, default=0, verbose_name='Stärke (in mm)'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='width',
            field=models.IntegerField(blank=True, default=0, verbose_name='Breite (in mm)'),
        ),
    ]
