# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20160118_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsawblade',
            name='heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Seitentitel'),
        ),
    ]
