# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 16:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_bandsawblade_cols'),
    ]

    operations = [
        migrations.CreateModel(
            name='JigSawBlade',
            fields=[
                ('sawblade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.SawBlade')),
                ('tooth_separation', models.FloatField(blank=True, verbose_name='Zahnteilung (ZpZ)')),
                ('cutting_metal', models.CharField(blank=True, max_length=255, verbose_name='Schnittbereich Metall')),
                ('cutting_wood', models.CharField(blank=True, max_length=255, verbose_name='Schnittbereich Holz')),
            ],
            options={
                'verbose_name': 'Pendelhubstichsägeblatt',
                'verbose_name_plural': 'Pendelhubstichsägeblätter',
            },
            bases=('products.sawblade',),
        ),
    ]
