# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_auto_20160122_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularSawBlade',
            fields=[
                ('sawblade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.SawBlade')),
            ],
            options={
                'verbose_name': 'Metallkreissägeblatt',
                'verbose_name_plural': 'Metallkreissägeblätter',
            },
            bases=('products.sawblade',),
        ),
        migrations.CreateModel(
            name='CircularSawBladeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Kennziffer')),
                ('diameter', models.IntegerField(blank=True, verbose_name='Durchmesser (in mm)')),
                ('strength', models.FloatField(blank=True, verbose_name='Stärke (in mm)')),
                ('bore', models.IntegerField(blank=True, verbose_name='Bohrung (in mm)')),
                ('BW_3', models.IntegerField(blank=True, verbose_name='BW 3 mm')),
                ('BW_4', models.IntegerField(blank=True, verbose_name='BW 4 mm')),
                ('HZ_5', models.IntegerField(blank=True, verbose_name='HZ 5 mm')),
                ('HZ_6', models.IntegerField(blank=True, verbose_name='HZ 6 mm')),
                ('BW_7', models.IntegerField(blank=True, verbose_name='BW 7 mm')),
                ('HZ_8', models.IntegerField(blank=True, verbose_name='HZ 8 mm')),
                ('HZ_9', models.IntegerField(blank=True, verbose_name='HZ 9 mm')),
                ('HZ_10', models.IntegerField(blank=True, verbose_name='HZ 10 mm')),
                ('HZ_12', models.IntegerField(blank=True, verbose_name='HZ 12 mm')),
                ('HZ_14', models.IntegerField(blank=True, verbose_name='HZ 14 mm')),
                ('NL', models.CharField(blank=True, max_length=255, verbose_name='NL in mm')),
            ],
            options={
                'verbose_name': 'Metallkreissägeblatt-Kennziffer',
                'verbose_name_plural': 'Metallkreissägeblatt-Kennziffern',
            },
        ),
        migrations.AlterModelOptions(
            name='bandsawbladeindicator',
            options={'verbose_name': 'Sägeband-Kennziffer', 'verbose_name_plural': 'Sägeband-Kennziffern'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('value',), 'verbose_name': 'Kennziffer', 'verbose_name_plural': 'Kennziffern'},
        ),
        migrations.AlterField(
            model_name='jigsawblade',
            name='length',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sägeblattlänge (in mm)'),
        ),
        migrations.AddField(
            model_name='circularsawblade',
            name='circular_indicators',
            field=models.ManyToManyField(blank=True, to='products.CircularSawBladeIndicator', verbose_name='Kenziffern'),
        ),
    ]
