# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_auto_20160123_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='description_de',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='description_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
