# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_auto_20160202_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsawblade',
            name='type2_description_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2. Typ Beschreibung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='type2_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2. Typ Beschreibung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='type2_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2. Typ Beschreibung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='type_description_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Typ Beschreibung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='type_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Typ Beschreibung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='type_description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Typ Beschreibung'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='category_de',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='category_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='category_ru',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='description_de',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='description_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='jigsawblade',
            name='subcategory_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='jigsawblade',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='jigsawblade',
            name='subcategory_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='description_de',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='description_ru',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Beschreibung'),
        ),
    ]
