# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_auto_20160208_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sablesawblade',
            name='cutting_minerals_de',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Schnittbereich Mineralisch'),
        ),
        migrations.AddField(
            model_name='sablesawblade',
            name='cutting_minerals_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Schnittbereich Mineralisch'),
        ),
        migrations.AddField(
            model_name='sablesawblade',
            name='cutting_minerals_ru',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Schnittbereich Mineralisch'),
        ),
    ]
