# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_auto_20160210_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='sablesawblade',
            name='toothing_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Verzahnung'),
        ),
        migrations.AddField(
            model_name='sablesawblade',
            name='toothing_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Verzahnung'),
        ),
        migrations.AddField(
            model_name='sablesawblade',
            name='toothing_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Verzahnung'),
        ),
    ]
