# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_auto_20160210_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacksawblade',
            name='subcategory_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='hacksawblade',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='hacksawblade',
            name='subcategory_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unterkategorie'),
        ),
    ]
