# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_auto_20160212_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='holesaw',
            name='mounting_de',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Aufnahmeschaft'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='mounting_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Aufnahmeschaft'),
        ),
        migrations.AddField(
            model_name='holesaw',
            name='mounting_ru',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Aufnahmeschaft'),
        ),
    ]
