# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_auto_20160212_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsawblade',
            name='heading_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seitentitel'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='heading_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seitentitel'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='heading_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seitentitel'),
        ),
    ]
