# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_auto_20160212_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsawblade',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung'),
        ),
    ]
