# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_auto_20160212_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandsawblade',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='bandsawblade',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='bandsawblade',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='sawblade',
            name='name_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung'),
        ),
    ]
