# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0078_auto_20160217_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsawblade',
            name='image2_de',
            field=models.ImageField(blank=True, null=True, upload_to='blades/', verbose_name='2. Produktabbildung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='image2_en',
            field=models.ImageField(blank=True, null=True, upload_to='blades/', verbose_name='2. Produktabbildung'),
        ),
        migrations.AddField(
            model_name='bandsawblade',
            name='image2_ru',
            field=models.ImageField(blank=True, null=True, upload_to='blades/', verbose_name='2. Produktabbildung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='image_de',
            field=models.ImageField(blank=True, null=True, upload_to='blades/', verbose_name='Produktabbildung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='blades/', verbose_name='Produktabbildung'),
        ),
        migrations.AddField(
            model_name='sawblade',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='blades/', verbose_name='Produktabbildung'),
        ),
    ]
